version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Sync local files with the container
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
